### PR TITLE
Recorded once queries are added to sink

### PR DESCRIPTION
**Pull request by ntl**
Recently, I came across a situation in the automated tests for `entity-cache` where I wanted to test that all the data in a single telemetry record matched what was expected. For context, we came across a similar challenge using the messaging writer substitute in tests -- we wanted to test that each attribute of a written message matched some control value. This lead us to implement `writer.one_message` on the writer substitute. This PR is bringing similar semantics to `telemetry`, with the added benefit that the writer substitute can be simplified if it uses the implementation of "get one and only one telemetry record" from this PR.

I was not quite able to fully grasp the semantics of the test prose, or the file naming approach in `test/automated/`. So, the automated tests are deserving of close scrutiny.

Anyways, the gist of what this PR adds:

```ruby
class SomeClass
  module Telemetry
    class Sink < ::Telemetry::Sink
      record :some_signal
    end
  end
end

telemetry_sink = SomeClass::Telemetry::Sink.build


telemetry_sink.record(:some_signal, Clock.now, 'some-value')

assert(telemetry_sink.recorded_once?)
assert(telemetry_sink.recorded_once? { |record| record.data.some_value == 'some-value' })
assert(telemetry_sink.recorded_some_signal_once?
assert(telemetry_sink.recorded_some_signal_once? { |record| record.data.some_value == 'some-value' })


telemetry_sink.record(:other_signal, Clock.now, 'some-value')
telemetry_sink.record(:other_signal, Clock.now, 'some-value')

refute(telemetry_sink.recorded_once?)
refute(telemetry_sink.recorded_once? { |record| record.data.some_value == 'some-value' })
refute(telemetry_sink.recorded_other_signal_once?
refute(telemetry_sink.recorded_other_signal_once? { |record| record.data.some_value == 'some-value' })
```

I am not sure whether "once" is the right word for the method names -- perhaps it should be `recorded_one` instead of `recorded_once`, and `recorded_one_some_signal` instead of `recorded_some_signal_once`. I found myself playing a lot of mental gymnastics with this one; input would be appreciated.

### CODE REVIEW

**Comment by sbellware** [comment]
Just for clarity... In the above example, `recorded_other_signal_once` couldn't work since it's not a registered recorded signal in the sink, right? ie: The meta-generation of those methods would only happen by having `record :other_signal` declared in the sink.

**Comment by sbellware** [comment]
Ultimately, I think we need to revisit the structure of the tests in this library. I'm not a fan, and it was annoying last time i worked in it.

**Comment by sbellware** [comment]
Looks good for a merge though. 🍏

**Comment by ntl** [comment]
Yes, that's correct, it was an error on my part. Only signals that are meant to be recorded (according to the `record` class macro) are, in fact, recorded.

**Pull request merged**
